# -*- coding: utf-8 -*-
"""Cold Mailing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kdzPR9j1ynpOZePa8X2ZRhy8wpd05gCD
"""

from google.colab import files

# Upload the file
uploaded = files.upload()

import os
file_path = os.path.join(os.getcwd(), 'Dummy_Resume.pdf')
print("Your File path is this",file_path)

import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
from os.path import basename
from email.utils import formatdate
from email import encoders
import pandas as pd
import time

#This function used pandas to take in the email list {sr no, name, registration, email}
def taking_values():
    sheet_name = 'Dummy Name'  # replace with sheet name
    sheet_id = 'xxxxx-_WQB5-x4FKR5oXvjeiSs2OotiOafVsDeXXXXX'  # replace with sheet ID. Its from d/ - /edit  #REPLACE THIS WITH WHATEVER SHEET YOU HAVE THAT HAS THE DATABASE

    url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}"
    data = pd.read_csv(url)

    # Convert each row into a list and embed those rows into a nested list A.
    A = data.values.tolist()
    number_of_rows=len(A)
    return (A)

#We have to send the mails using SMTP server. Please do not change anything below until said
def send_email(subject, message, from_addr, to_addr, cc_addr, app_password, attachments=None):
    msg = MIMEMultipart()
    msg['From'] = from_addr
    msg['To'] = to_addr
    msg['CC'] = cc_addr
    msg['Subject'] = subject
    msg['Date'] = formatdate(localtime=True)

    body = message

    msg.attach(MIMEText(message, 'html'))



    if attachments:
        for attachment in attachments:
            with open(attachment, 'rb') as f:
                part = MIMEApplication(f.read(), Name=basename(attachment))
            part['Content-Disposition'] = f'attachment; filename="{basename(attachment)}"'
            msg.attach(part)

    server = smtplib.SMTP('smtp.gmail.com', 587)
    server.starttls()
    server.login(from_addr, app_password)
    text = msg.as_string()
    server.sendmail(from_addr, [to_addr] + [cc_addr], text)
    server.quit()

def attachment(file_path):
    return file_path

def main():
    #pg.alert(text='Start the mailing?', title='', button='OK')
    # Email details from the sheets
    names = taking_values()

    subject = "SUBJECT OF THE MAIL" #This line asks the user for entering the subject

    from_addr = "YOUR EMAIL" #This code asks the user to enter their mail id, with which they have to send the mails

    app_password = "ENTER THE PASSWORD" #This line of code asks for the passwroed from the user

    num_cc = 0 #we need the count of number of people to be CC'ed
    cc_addrs = []
    for i in range(num_cc):#this section deals with CCing x number of people
        cc_addr = ""#pg.prompt(text=f'Enter CC email {i+1}', title='Enter CC email', default='')
        cc_addrs.append(cc_addr)
    ## changes again here
    for to_add in names:#This is where the magic happens. where the mials are sent
        attachments = [file_path]#Your can change the location of the file. Mind you, it should be between the r' '
        to_addr = to_add[3]
        name = to_add[1]
        #There's a unique way to write this message, will teach you in the meeting
        message_html = f"""
        <html>
        <body>
        <p>Dear {name},</p>

        <p>I'm writing to express my keen interest in applying for a <b>Research Assistant</b> position under your guidance. As a student majoring in <b>Economics</b>, <b>Mathematics</b>, and <b>Statistics</b> at DUMMY University KARNATAKA, this opportunity would allow me to deepen my understanding of economic research and contribute meaningfully to your ongoing projects.</p>
        <!-- Add hyperlinks -->

        <p>My experience as a <b>Research Analyst</b> at <b>Quantace Research</b>, where I evaluated economic impacts and regulatory frameworks surrounding the <b>Transferable Development Rights (TDR) Exchange</b>, and as the <b>Head of Research and Development</b> at <b>The Lantern Tribe</b>, where I led cross-functional teams to provide data-driven insights for strategic growth, has honed my skills in <b>data analysis</b>, <b>economic modeling</b>, and <b>research methodology</b>. These experiences, coupled with my academic background, make me a strong candidate for the <b>Research Assistant position</b>.</p>

        <p>My academic journey has equipped me with <b>technical skills</b> like <b>statistical analysis</b>, <b>research methodology</b>, and <b>data visualization</b>. My background in <b>economic analysis</b> and <b>research development</b> background positions me well to assist with <b>data collection</b>, <b>literature reviews</b>, and <b>empirical analysis</b>. I am particularly interested in contributing to research that addresses critical economic issues and advances our understanding of complex economic phenomena.</p>

        <p>I am truly excited about the possibility of <b>contributing to your research projects</b> and learning from your expertise. Thank you for considering my application. I am eager to discuss how my skills and passion can align with your research goals.</p>
        <!-- Add your sign-off with an image -->
        <p>Looking forward to meeting you or connecting with your Learning Team.</p>
        <p>Best regards,<br>
        <a href=" ATTACH UR LINKEDIN PROFILE LINK"> NAME</a><br></br></p>
        </body>
        </html>
        """

        send_email(subject, message_html, from_addr, to_addr, ', '.join(cc_addrs), app_password, attachments=attachments)
        print(f'Email sent to {to_addr}')
main()
